# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pc/Desktop/lab3/lab6_1_3/lab6_1_3.cache/wt [current_project]
set_property parent.project_path C:/Users/pc/Desktop/lab3/lab6_1_3/lab6_1_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/pc/Desktop/lab3/lab6_1_3/lab6_1_3.srcs/sources_1/new/delay_line1_behavior.v
synth_design -top delay_line1_behavior -part xc7vx485tffg1157-1
write_checkpoint -noxdef delay_line1_behavior.dcp
catch { report_utilization -file delay_line1_behavior_utilization_synth.rpt -pb delay_line1_behavior_utilization_synth.pb }
