# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/lab3/1001/jiance/jiance.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/lab3/1001/jiance/jiance.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/lab3/1001/jiance/jiance.srcs/sources_1/new/d_ff.v
  C:/Users/Administrator/Desktop/lab3/1001/jiance/jiance.srcs/sources_1/new/jiance.v
}
synth_design -top jiance -part xc7vx485tffg1157-1
write_checkpoint -noxdef jiance.dcp
catch { report_utilization -file jiance_utilization_synth.rpt -pb jiance_utilization_synth.pb }
