# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/lab3/lab5_1_2/lab5_1_2.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/lab3/lab5_1_2/lab5_1_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/lab3/lab5_1_1/lab5_1_1.srcs/sources_1/new/SR_latch_dataflow.v
  C:/Users/Administrator/Desktop/lab3/lab5_1_2/lab5_1_2.srcs/sources_1/new/lab5_1_2.v
}
synth_design -top lab5_1_2 -part xc7vx485tffg1157-1
write_checkpoint -noxdef lab5_1_2.dcp
catch { report_utilization -file lab5_1_2_utilization_synth.rpt -pb lab5_1_2_utilization_synth.pb }
