# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pc/Desktop/lab45/lab5_1_3/lab5_1_3.cache/wt [current_project]
set_property parent.project_path C:/Users/pc/Desktop/lab45/lab5_1_3/lab5_1_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/pc/Desktop/lab45/lab5_1_3/lab5_1_3.srcs/sources_1/new/next_out_rom.v
  C:/Users/pc/Desktop/lab45/lab5_1_3/lab5_1_3.srcs/sources_1/new/counter_rom.v
}
synth_design -top counter_rom -part xc7vx485tffg1157-1
write_checkpoint -noxdef counter_rom.dcp
catch { report_utilization -file counter_rom_utilization_synth.rpt -pb counter_rom_utilization_synth.pb }
