# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pc/Desktop/lab3/lab5_2_5/lab5_2_5.cache/wt [current_project]
set_property parent.project_path C:/Users/pc/Desktop/lab3/lab5_2_5/lab5_2_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/pc/Desktop/lab3/lab5_2_5/lab5_2_5.srcs/sources_1/new/T_ff_enable_behavior.v
synth_design -top T_ff_enable_behavior -part xc7vx485tffg1157-1
write_checkpoint -noxdef T_ff_enable_behavior.dcp
catch { report_utilization -file T_ff_enable_behavior_utilization_synth.rpt -pb T_ff_enable_behavior_utilization_synth.pb }
