# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.cache/wt [current_project]
set_property parent.project_path C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.srcs/sources_1/new/rom.v
  C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.srcs/sources_1/new/comparator.v
  C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.srcs/sources_1/new/Register.v
  C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.srcs/sources_1/new/adder.v
  C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.srcs/sources_1/new/MUX21.v
  C:/Users/pc/Desktop/lab45/lab4_2/lab4_2.srcs/sources_1/new/lab4_2.v
}
synth_design -top lab4_2 -part xc7vx485tffg1157-1
write_checkpoint -noxdef lab4_2.dcp
catch { report_utilization -file lab4_2_utilization_synth.rpt -pb lab4_2_utilization_synth.pb }
