.386
CODE	SEGMENT	USE16
	ASSUME	CS:CODE, SS:STACK
OLD_INT	DW	?,?
;新中断处理程序（“INT 16H”）的代码
NEW16H:	PUSHF
	CALL	DWORD PTR OLD_INT
	CMP	AL, 41H
	JE	ATB
	CMP	AL, 42H
	JE	BTA
LAST:	IRET
ATB:	MOV	AL, 42H
	JMP	LAST
BTA:	MOV	AL, 41H
	JMP	LAST	

;初始化（安装新中断矢量并常驻内存）程序
START:	XOR	AX, AX
	MOV	DS, AX
	MOV	AX, DS:[16H * 4]
	MOV	OLD_INT, AX
	MOV	AX, DS:[16H * 4 + 2]
	MOV	OLD_INT+2, AX
	CLI
	MOV	WORD PTR DS:[16H * 4], OFFSET NEW16H
	MOV	DS:[16H * 4 + 2], CS
	STI						;开中断
	MOV	DX, OFFSET START+15
	SHR	DX, 4
	ADD	DX, 10H
	MOV	AL, 0
	MOV	AH, 31H
	INT	21H
CODE	ENDS
STACK	SEGMENT	STACK	USE16
	DB	200	DUP(0)
STACK	ENDS
	END	START
